image:
  repository: stuartnelson3/webhook
  tag: latest
  pullPolicy: Always
  pullSecrets: []

certPath: /opt/webhook/certs
certFile: cert.pem
keyFile: key.pem
apm:
  # how do users get to this? secrets are namespace bound
  namespace: default
  token: abc123 # TODO: Make this a required variable

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}

webhookConfig:
  agents:
    java:
      image: docker.elastic.co/observability/apm-agent-java:1.23.0
      environment:
        ELASTIC_APM_SERVER_URLS: "http://34.78.173.219:8200"
        ELASTIC_APM_SERVICE_NAME: "petclinic"
        ELASTIC_APM_ENVIRONMENT: "test"
        ELASTIC_APM_LOG_LEVEL: "debug"
        ELASTIC_APM_PROFILING_INFERRED_SPANS_ENABLED: "true"
