image:
  repository: stuartnelson3/webhook
  tag: latest
  pullPolicy: Always
  pullSecrets: []

certPath: /opt/webhook/certs
certFile: cert.pem
keyFile: key.pem
apm:
  # how do users get to this? secrets are namespace bound
  namespace: default
  token: abc123 # TODO: Make this a required variable

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}
