image:
  repository: stuartnelson3/webhook
  tag: latest
  pullPolicy: Always
  pullSecrets: []

certFile: cert.pem
keyFile: key.pem
apm:
  # how do users get to this? secrets are namespace bound
  namespace: default
  token:

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}

webhookConfig:
  agents:
    java:
      image: docker.elastic.co/observability/apm-agent-java:latest
      artifact: "/usr/agent/elastic-apm-agent.jar"
      environment:
        ELASTIC_APM_LOG_LEVEL: "info"
        ELASTIC_APM_PROFILING_INFERRED_SPANS_ENABLED: "false"
